[package]
name = "mpv-egui-musicplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-sfml = "0.2.0"
pty-process = { git = "https://github.com/crumblingstatue/pty-process.git", branch = "quickfix" }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
directories = "4.0.1"
rfd = "0.10.0"
walkdir = "2.3.2"
nonblock = "0.2.0"
ansi_term_buf = { git = "https://github.com/crumblingstatue/ansi_term_buf.git" }
ksni = { git = "https://github.com/iovxw/ksni.git" }
thiserror = "1.0.37"
enum-kinds = "0.5.1"
interprocess = { version = "1.2.1", default-features = false }
anyhow = "1.0.66"

[profile.dev.package."*"]
opt-level = 2
